### ISSUE TITLE
MissingContentOrMetadataFile

### ISSUE THREAD

**Issue by sfdcschwabe** [LawrenceLoz/FormulaShare-DX#11]
Following metadata files are missing in current repository branch 'master':
- FormulaShare-DX/fs-core/main/default/classes/FormulaShareSObjectSharesStdSelector.cls-meta.xml
- FormulaShare-DX/fs-core/main/default/classes/FormulaShareSObjectSharesCustomSelector.cls-meta.xml

**Comment by LawrenceLoz** [comment]
Thanks Christian, these are legacy classes and shouldn't be in the repo - I've removed with the latest commit
