### ISSUE TITLE
Feature Request: Using base components for formulaShareNoRulesIllustration.js

### ISSUE THREAD

**Issue by sfdcschwabe** [LawrenceLoz/FormulaShare-DX#13]
**What is missing from the application? Please describe.**

Using lightning base component instead of own styling with css classes from slds.

**Describe the solution you'd like**

Regarding the fs-core/main/default/lwc/formulaShareNoRulesIllustration/formulaShareNoRulesIllustration.js I would like to suggest using the following base components:
- lightning-card

**Describe alternatives you've considered**

**Additional context**

**Comment by sfdcschwabe** [comment]
Current state:
![image](https://user-images.githubusercontent.com/58388000/101239589-e52a4f80-36e8-11eb-86c7-e8b306ecb1f2.png)

**Comment by sfdcschwabe** [comment]
After the change:
![image](https://user-images.githubusercontent.com/58388000/101239678-d09a8700-36e9-11eb-8e51-2ab5c2ead43d.png)

**Comment by LawrenceLoz** [comment]
Delivered through https://github.com/LawrenceLoz/FormulaShare-DX/pull/14. Thanks @sfdcschwabe!
