### ISSUE TITLE
Enhancement: Make components more standalone and independent

### ISSUE THREAD

**Issue by sfdcschwabe** [LawrenceLoz/FormulaShare-DX#15]
A lwc - in my opinion - should care of it's visibility state itself. I my architecture thinking this makes the components more standalone and independent.

Current approach (in formulaShareRulesListView.html):
![image](https://user-images.githubusercontent.com/58388000/101378802-d5129b80-38b3-11eb-828c-a15f50ae6c02.png)

Suggestion:
Move <template if:true={...}></template> to the child component and call an @api annotated method in the child to show/hide the content of the child component.

**Comment by LawrenceLoz** [comment]
Hey Christian thanks for the suggestion. I think I see it a little differently though - that it should be the responsibility of the wider context whether or not a component is required for the page and should render it only if required.

There's a few things I think are improved by controlling whether the component is rendered in its parent:
 - The child component should have minimum awareness of the context it's called to have the most independence and to simplify investigating issues - having an extra @api method increases the interactions and awareness the child has of the parent
 - The child isn't loaded into the DOM if it's not needed, so it's clear in debug tools that this component isn't used on the page. Similar considerations with JS source of the child component
 - The approach you describe isn't taken in the design pattern of base components, so an approach to show/hide these (e.g. the lightning-spinner in the screenshot) would have to work differently and would make the overall solution less consistent

Does this make sense to you and is there anything I've not thought about you think's worth considering?

**Comment by sfdcschwabe** [comment]
Hi Lawrence

I like the discussion about the best approaches (weighing up the advantages and disadvantages) for different scenarios and ask yourself everytime: Is this the best you can do? Research for other solutions and try to find someone who has a better idea about the same problem.

I had the hope to find a verified answer in this article (https://developer.salesforce.com/blogs/2020/06/lightning-web-components-performance-best-practices.html), especially round about the headline 'Conditional Rendering' but unfortunately not.
I think your argument with the lightning-spinner is pretty accurate. If they had considered my approach in the base-components, the call for shod/hide the lightning-spinner would have to look different.
I found your used approach in the dreamhouse sample app: https://github.com/trailheadapps/dreamhouse-lwc/blob/master/force-app/main/default/lwc/propertyCarousel/propertyCarousel.html

I think your approach is a better solution with the given arguments and design patterns who are taken into account for lightning base components!

**Comment by LawrenceLoz** [comment]
Hi Christian,

Completely agree, this is the interesting side of development for me too! Always keen to find ways to improve and it's great to get your input and thoughts around things which could be better. I'm not precious about any of the decisions taken so far so don't see anything as set in stone - please do suggest where you spot things which could be better and we can make a call on where and how to improve.

And thanks for the links, Dreamhouse is always a good reference point. Not perfect I'm sure but a good way to see how Salesforce themselves envisage best practices on the platform. I've realised looking at that file I think I've seen the "c-error-panel" being used this way in documentation before - I'll send a link your way if I remember where or come across it again

**Comment by LawrenceLoz** [comment]
Hey @sfdcschwabe, just came across the documentation link I was looking at before, might be interesting - https://developer.salesforce.com/blogs/2020/08/error-handling-best-practices-for-lightning-web-components.html
