### ISSUE TITLE
Enhancement: Global method for asynchronous sharing recalculation

### ISSUE THREAD

**Issue by LawrenceLoz** [LawrenceLoz/FormulaShare-DX#22]
Subscriber orgs can create a FormulaShareHelper class and call global methods on this to add and remove share records in real time.

Currently this only works within a synchronous trigger context.

This should be made more flexible so that it's possible to efficiently reassess sharing from a queueable method call (this is the target use case as it's a current enhancement request)

**Comment by LawrenceLoz** [comment]
Will need to support the following:
 - Call with list or map of records (for async processes following insert and undelete, calling on demand for records, and as a full-reassessment version after record updates)
 - Call with list or map of new records, and a list/map of old records (for async processes following update)
Global class for calling FS currently is /fs-core/main/default/classes/FormulaShareTriggerHelper.cls. We may want to adapt this or potentially create a new one

**Comment by LawrenceLoz** [comment]
Release branch to branch from: https://github.com/LawrenceLoz/FormulaShare-DX/tree/Release_Feb21
https://gist.github.com/CristinaSolana/1885435

As per discussion, we think 3 new classes needed:
FormulaShareIAsyncHelper - Interface to enable dynamic construction / execution of processor classes
FormulaShareAsyncHelperProcessor - Public class, extends FormulaShareHelper and calls super.handleChanges() with records passed from global
FormulaShareAsyncHelper - Global class with logic to check custom metadata

These would be equivalent to current classes for trigger context:
FormulaShareIHelper
FormulaShareTriggerHelper
FormulaShareHelper

**Comment by LawrenceLoz** [comment]
Branch name format: #022_Async_Recalculation

**Comment by thegee** [comment]
I'm having problems creating a scratch org from my new branch. Pls find below the errors msg.
I have googled the error message and it all points me to enable DevHub. Which I have done. I'm able to create scratch org with old FS git repo and other scratch orgs too. Not sure what is going on. Any help would be appreciated.
± |#022_Async_Recalculation ?:2 ✗| → sfdx force:org:create -f config/project-scratch-def.json -a FSLabs --setdefaultusername

ERROR running force:org:create:  You do not have access to the [**ScratchOrgInfo**] object

**Comment by LawrenceLoz** [comment]
Hey George - I've just responded over email, hopefully we can get this ironed out

**Comment by gwiafe** [comment]
@LawrenceLoz, Pls find my  current feature branch for issue:#022
https://github.com/gwiafe/FormulaShare-DX/tree/022_Async_Recalculation
I updated: FormulaShareHelper and added a new class FormulaShareAsyncHelperProcessor. Just need you to review the approach to make sure, am on the right path from our discussion. Currently writing unit test and testing with FSSampleQueueableService.

**Comment by LawrenceLoz** [comment]
Hi @gwiafe 
Thanks and looks great! I've added some comments on the commit: https://github.com/LawrenceLoz/FormulaShare-DX/commit/62512326c220e22923f3dfd2ab7b245f4e6e3b74
