### ISSUE TITLE
Option in UI to change whether standard object has sharing removed

### ISSUE THREAD

**Issue by LawrenceLoz** [LawrenceLoz/FormulaShare-DX#29]
The custom metadata type `FormulaShare_Std_Object_to_Remove_Shares__mdt` controls whether share records (including all apex and manual sharing) are removed by FormulaShare on each standard object.

It would be helpful to control whether or not this is enabled from the user interface.

An option "Change Sharing Removal Setting" could be added as a dropdown on the rules list view for standard objects. This should open a popup showing the current setting and explaining the effect of changing.

**Comment by sfdcschwabe** [comment]
Hi @LawrenceLoz

I try to start working on this issue, prepare a scratch org an during the push I have again very similiar problems in the beginning like the last time.

In master is a class named 'fs-core/main/default/classes/FormulaShareSObjectSharesStdSelector.cls', but the metadata file is missing. I remember your answer this class is not needed anymore. For this reason I've deleted this class. But when I delete this class and try to push again I get the following error:
`MissingContentOrMetadataFile: Expected file at path: /Users/christianschwabe/Documents/Visual Studio Code/FormulaShare-DX/fs-core/main/default/classes/FormulaShareSObjectSharesStdSelector.cls-meta.xml`

**Comment by sfdcschwabe** [comment]
It seems the error is a subsequent fault because FormulaShareSObjectSharesCustomSelector.cls-meta.xml is also missing in master.
I've deleted both files and the push worked now.

**Comment by sfdcschwabe** [comment]
As mentioned above, I now use a scratch org, which is still a bit bulky. I am currently not able to push the sample app. Do you know why that could be?

I already have to change the default parameter from false to true in the sfdx-project.json for "package": "FS-Sample-App". However, this did not bring the desired success.

**Comment by LawrenceLoz** [comment]
Hi @sfdcschwabe, it looks like your first error may be because your git working directory wasn't clean before checking out master (or possibly because you haven't pulled latest changes from the branch) - both files are removed from master.

What error are you seeing deploying the sample app? I'm able to deploy this locally and I've just run the validate branch job on master which is able to deploy this successfully as well https://github.com/LawrenceLoz/FormulaShare-DX/actions/runs/731855556

If you're using SFDX recommend updating to the latest version and defaulting to SOAP, there are some widespread issues with REST https://github.com/forcedotcom/cli/issues/860

**Comment by sfdcschwabe** [comment]
Hi @LawrenceLoz

Of course, I had previously performed a pull on the master branch. Apparently, however, that was not enough. Today I did a pull (rebase) on the master and then the last commit was identical to that of the master remote branch.
After the next push, no difference was noticeable.
When executing runApexFullTestDataset.apex the error message came up:
```
08: 48: 00.974 Starting Execute Anonymous Apex

Error: Line: 2, Column: 1
Error: Variable does not exist: FSSampleAppDataGenerationService
```

VSC says:
`Variable does not exist: FSSampleAppDataGenerationService/Users/xxx/Documents/Visual Studio Code/FormulaShare-DX/config/runApexFullTestDataset.apex`

It seems VSC is not able to recognize the right path?
the class FSSampleAppDataGenerationService.cls is already pushed into my scratch org.

**Comment by LawrenceLoz** [comment]
Hmmm odd. Are you running this as part of the buildTestOrg.sh script or trying to execute on its own? If on its own what's the exact command line command you're using? (should be something like sfdx force:apex:execute -f config/runApexOnInstallation.apex -u scratchOrgName)

I'm using windows so it's hard for me to dig into this. My workflow is to run buildScratchOrg.bat which creates the org, deploys everything and then runs runApexFullTestDataset.apex which all works correctly

**Comment by sfdcschwabe** [comment]
You bring me back on the right track and remind me to use buildScratchOrg.sh.
I've forgotten the script.
Yesterday I've used 'SFDX: Push Source to Default Scratch Org' in VSC, but this seems to push only the metadata and not the sample app.

**Comment by sfdcschwabe** [comment]
Hi @LawrenceLoz 

Now that the barriers to entry have been overcome, I've moved on to the actual requirement.
Can you give me some more background on FormulaShare_Std_Object_to_Remove_Shares__mdt?
The description of the FormulaShare_Std_Object_to_Remove_Shares__mdt.Standard_Object_to_Remove_Sharing__c field says an entry from a standard object will cause all shares on that object to be deleted, correct? That means specifically all except the record ownership based shares are deleted?
Is it intended to manually enter such a record in this Custom Metadata Type? Is there a UI that populates this Custom Metadata Type?

No matter how an entry gets into this Custom Metadata Type, this entry cannot trigger any automation. Is this why the formulated issue exists?

Why should the selection to open the modal window only be available for Standard Objects?
If this should be the case and it should only be possible to delete the shares for Standard Objects, a dynamic check of the configuration from rules list view must be done first, which checks if it is a Standard Object, right?
Also, should the organization-wide share model of that object (is that even possible?), which must have at least Public Read or below, be checked to show the menu item?

I have created a small mockup to explain the UI of the modal window for better visualization to align us better.
![image](https://user-images.githubusercontent.com/58388000/114269219-f91eee80-9a05-11eb-97c2-f0bfbf2dcef4.png)

Should there be a reconfirmation after clicking the destructive button, along the lines of "Do you really want to perform this action?"

Is it at all possible to delete approval data records that are based on approval rules using Apex?
How exactly do you imagine the deletion process for these releases? From my point of view, it has to be a batch job.
Should the progress of the deletion be visualized somewhere, according to the principle x of y data records were deleted?

I hope I haven't flooded you with questions. But they are necessary so that I have a better understanding of your expectations. I hope this is okay for you. :)


Best regards,
Christian

**Comment by LawrenceLoz** [comment]
Hi Christian,

Glad the deployment problems are sorted now.

The help section here should hopefully explain what this metadata type is for and answer some of your questions: https://cloudsundial.com/formulashare-standard-object-options

Basically, if a record exists in this metadata type for the object then every time a record of this object is processed, every share record will be deleted other than any other than ones matching the current sharing for any rules sharing the object. This will include any sharing previously applied by the rules as well as programmatic sharing created outside of FormulaShare and any manual sharing too.

The help page explains the challenge around lack of apex sharing reasons on standard objects which is why this is needed on standard objects and not custom.

So, to answer your questions which aren't covered above or in the page:
 - There's no UI to set records at the moment, subscribers need to manage the custom metadata records directly themselves. The objective of this ticket is to provide the UI to do this
 - I don't think we need to worry about checking the organisation-wide sharing for the object so long as the modal is launched from the object's line in the rules list tree grid

In my view, the simplest way to deliver this would be:
 - Add a row action to the tree grid (maybe "Change Sharing Removal Strategy") in the formulashare rules list component
 - Action launches a Sharing Removal Strategy modal with an explanation of the effect of changing removal strategy, and a toggle to do this ("Enable Fully Managed Sharing"). Explanation could be something like:
 "By default FormulaShare won't remove any existing sharing on standard objects when applying new sharing, which means any sharing applied by FormulaShare won't be automatically removed if the scope of the rules changes.
Alternatively, the Fully Managed Sharing strategy can be applied, which means any existing sharing not matching current FormulaShare rules is removed each time the record is processed by FormulaShare. For more details on these options, check the <help guide> (links to https://cloudsundial.com/formulashare-standard-object-options)"
 - We'll probably want a new field on the custom metadata type to allow an existing custom metadata record to be disabled. We can't delete custom metadata records using apex, and if someone clicks the action for an object where this is enabled we want to show that it's enabled and give them an option to disable

I'm open to other ideas though if you have suggestions to do anything differently.

Thanks Christian

**Comment by sfdcschwabe** [comment]
Hi @LawrenceLoz,

no big deal until now, just to keep you informed - the current implementation (without any functionality):
![image](https://user-images.githubusercontent.com/58388000/114462931-0691cf80-9be4-11eb-9680-ec858dea2d02.png)

I've researched and think about how to update cmdt in apex. The only way I know is to do it with metadata deployment. But I think this is not the way you've planned to do it, right?
I think I get it to work to load the cmdt if a corresponding records exists by using the already existing selector class FormulaShareRemoveSharesSelector.cls
FormulaShareRemoveSharesSelector.cls returns a List of FormulaShare_Std_Object_to_Remove_Shares__mdt but in my mind there should only be one record for a Standard_Object_to_Remove_Sharing__r.QualifiedApiName. Why does it return a list?

Can you give me a hint how to trigger the update for cmdt when I click the toogle?
I've already created a new field (FormulaShare_Std_Object_to_Remove_Shares__mdt.Active__c).

**Comment by LawrenceLoz** [comment]
Hi Christian, thanks for sharing - this looks great so far.

It's possible to create and update custom metadata from apex using capabilities in the metadata namespace - https://trailhead.salesforce.com/en/content/learn/modules/apex_metadata_api/apex_metadata_api_tool. The AppExchange security review won't allow us to use the metadata API directly from within the package so this is the only option really.

We use this approach to create and update metadata records for the formulashare rules. I'd suggest taking a look at the classes FormulaShareRuleDMLController and FormulaShareRulesMetadataDMLService, which prepare and submit metadata for creation/update as well as emitting platform events on success and failure. Components like formulaShareRuleCreate.js subscribe to FormulaShare_Rule_DML__e events and react based on success or failure, so having something similar would make sense here I think.

And you're right that FormulaShareRemoveSharesSelector doesn't need to return a list - happy for you to change this if you like.

Oh and one last thing - although it's a little less intuitive, I think we will need the new field to be something like "Disabled" rather than "Active" - for orgs which are upgrading to the new package, we want their existing rules to be treated as active but I don't think we can have this field set to true for existing records.

Thanks
