### ISSUE TITLE
Sometimes the Share records are created, other times they are not (when using a real-time trigger)

### ISSUE THREAD

**Issue by brian-summit** [LawrenceLoz/FormulaShare-DX#49]
Thank you for creating an amazing solution.

We recently implemented the real-time trigger to ensure immediate access to newly-created records.  This was necessary because an external, web-based front-end is making API calls back to Salesforce (using a Service Account) to create records on behalf of someone.  Because the Ownership of the records is the Service Account, we need the trigger to quickly grant access to the Public Group so that way the members in the Public Group can access the record immediately in Salesforce.

We're seeing mixed results.  And they are easily and reliably reproducible.

When it doesn't work, the API debug logs are generated in this order:

- 05/20 13:16:05 /services/data/v36.0/sobjects/HOC__Volunteer_Opportunity__c  
- 05/20 13:16:07 /services/data/v36.0/sobjects/HOC__Scheduler__c  
- 05/20 13:16:10 /services/data/v36.0/composite/tree/HOC__Scheduler_Day__c  
- 05/20 13:16:13 /services/data/v36.0/sobjects/HOC__Volunteer_Opportunity__c/a0N4W00000TEceWUAT  
- 05/20 13:16:20 Api
- 05/20 13:16:21 Api

When it does work, the API debug logs are generated in this order:

- 05/20 13:28:55 /services/data/v36.0/sobjects/HOC__Volunteer_Opportunity__c
- 05/20 13:28:57 /services/data/v36.0/composite/tree/HOC__Occurrence__c	
- 05/20 13:28:59 /services/data/v36.0/sobjects/HOC__Volunteer_Opportunity__c/a0N4W00000TEcelUAD

	

Basically, it acts differently when two types of Volunteer Opportunities (HOC__Volunteer_Opportunity__c) are being created.  We do not have access to the code that is doing the API calls.

The debug logs are not revealing much, but it does appear that multiple DML operations are occurring on the HOC__Volunteer_Opportunity__c object.  Sometimes, no changes are detected and it seems to have an early exit point:

- 13:16:07.240 (2240016001)|CODE_UNIT_STARTED|[EXTERNAL]|01q4W0000021vLd|VolunteerOpportunityTrigger on Volunteer_Opportunity trigger event AfterInsert|__sfdc_trigger/VolunteerOpportunityTrigger
- 13:16:07.240 (2240073417)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
- 13:16:07.240 (2240140327)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
- 13:16:07.240 (2240164990)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
- 13:16:07.240 (2240172529)|STATEMENT_EXECUTE|[1]
- 13:16:07.240 (2240174961)|STATEMENT_EXECUTE|[2]
- 13:16:07.240 (2240190801)|HEAP_ALLOCATE|[2]|Bytes:8
- 13:16:07.240 (2240208344)|CONSTRUCTOR_ENTRY|[2]|01p4W00000Kg2Yi|<init>()|sdfs.FormulaShareHelper
- 13:16:07.240 (2240216745)|ENTERING_MANAGED_PKG|sdfs
- 13:16:07.240 (2241274459)|CONSTRUCTOR_EXIT|[2]|01p4W00000Kg2Yi|<init>()|sdfs.FormulaShareHelper
- 13:16:07.240 (2241298820)|STATEMENT_EXECUTE|[3]
- 13:16:07.240 (2241316393)|METHOD_ENTRY|[3]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.getSharesToInsert()
- 13:16:07.240 (2241323071)|ENTERING_MANAGED_PKG|sdfs
- 13:16:07.240 (2256883357)|ENTERING_MANAGED_PKG|sdfs
- 13:16:07.240 (2257048253)|METHOD_EXIT|[3]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.getSharesToInsert()
- 13:16:07.240 (2257061723)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
- 13:16:07.240 (2257117706)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
- 13:16:07.240 (2257124095)|STATEMENT_EXECUTE|[4]
- 13:16:07.240 (2257141519)|METHOD_ENTRY|[4]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.getSharesToDelete()
- 13:16:07.240 (2257147848)|ENTERING_MANAGED_PKG|sdfs
- 13:16:07.240 (2257175248)|ENTERING_MANAGED_PKG|sdfs
- 13:16:07.240 (2257250103)|METHOD_EXIT|[4]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.getSharesToDelete()
- 13:16:07.240 (2257257260)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
- 13:16:07.240 (2257281961)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
- 13:16:07.257 (2257292387)|CUMULATIVE_LIMIT_USAGE
- 13:16:07.257 (2257292387)|LIMIT_USAGE_FOR_NS|(default)|

Other times, it seems like FormulaShare finds some rules that need to be implemented, and it does its thing:

- 13:16:06.310 (1310091865)|CODE_UNIT_STARTED|[EXTERNAL]|01q4W0000021vLd|VolunteerOpportunityTrigger on Volunteer_Opportunity trigger event AfterUpdate|__sfdc_trigger/VolunteerOpportunityTrigger
- 13:16:06.310 (1310171891)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
- 13:16:06.310 (1310184922)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
- 13:16:06.310 (1313160661)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
- 13:16:06.310 (1313261680)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:8
- 13:16:06.310 (1313275103)|STATEMENT_EXECUTE|[1]
- 13:16:06.310 (1313278447)|STATEMENT_EXECUTE|[2]
- 13:16:06.310 (1313327003)|HEAP_ALLOCATE|[2]|Bytes:21
- 13:16:06.310 (1313336520)|HEAP_ALLOCATE|[2]|Bytes:8
- 13:16:06.310 (1313488639)|METHOD_ENTRY|[24]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.FormulaShareHelper()
- 13:16:06.310 (1313506746)|STATEMENT_EXECUTE|[24]
- 13:16:06.310 (1313513130)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1314292271)|METHOD_EXIT|[24]|sdfs.FormulaShareHelper
- 13:16:06.310 (1314329967)|HEAP_ALLOCATE|[2]|Bytes:8
- 13:16:06.310 (1314454255)|CONSTRUCTOR_ENTRY|[2]|01p4W00000Kg2Yi|<init>()|sdfs.FormulaShareHelper
- 13:16:06.310 (1314480093)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1324639644)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1324729975)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1326777985)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1326922218)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1327005645)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1327181265)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1327209346)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1327261337)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1327331190)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1330671580)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1330834075)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1331248738)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1331330383)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1331465269)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1331560674)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1331743605)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1331827636)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1331852939)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1333790011)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1333867250)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1335128452)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1335213219)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1335980729)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1336098455)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1336917771)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1337204863)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1337426986)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1337709057)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1337928036)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1338034104)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1338278698)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1338490036)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1338702217)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1338898184)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1339094951)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1339279663)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1339505377)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1339729933)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1339787856)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1339834044)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1340669250)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1340727835)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1340765678)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1341152480)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1341236624)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1341316077)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1341427703)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1341447337)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1341504512)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1341528352)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1342450046)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1342520231)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1342865565)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344058655)|HEAP_ALLOCATE|[478]|Bytes:10
- 13:16:06.310 (1344156941)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344210893)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344265945)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344281878)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344311902)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344412570)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344429988)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344458452)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344519303)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344541044)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344822913)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1344960407)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1345026523)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1345074309)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1345256296)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345269574)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345275956)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345281143)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345286220)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345291053)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345296103)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345301326)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345306440)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345312994)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345318124)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345322890)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345328002)|HEAP_ALLOCATE|[654]|Bytes:5
- 13:16:06.310 (1345335734)|HEAP_ALLOCATE|[654]|Bytes:441
- 13:16:06.310 (1345375476)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1345656007)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1346703930)|SOQL_EXECUTE_BEGIN|[131]|Aggregations:0|SELECT DeveloperName, sdfs__All_Record_Errors_Report_Name__c, sdfs__All_Record_Logs_Report_Name__c, sdfs__Batch_Errors_Report_Name__c, sdfs__Days_to_Retain_Batch_Logs__c, sdfs__Days_to_Retain_Record_Logs__c, sdfs__Log_Processing_Events__c, sdfs__Logs_Removal_Batch_Size__c, sdfs__Rec_Errors_Since_Last_Batch_Report_Name__c, sdfs__Recalculation_Batch_Size__c, sdfs__Record_Logs_Since_Last_Batch_Report_Name__c, sdfs__Trigger_Helper_Class_Override__c FROM sdfs__FormulaShare_Settings__mdt WHERE Active__c = true ORDER BY DeveloperName ASC NULLS FIRST 
- 13:16:06.310 (1351922378)|SOQL_EXECUTE_END|[131]|Rows:1
- 13:16:06.310 (1352775868)|METHOD_ENTRY|[22]|01p4W00000Kg2ZW|sdfs.FormulaShareTriggerHelper.FormulaShareTriggerHelper()
- 13:16:06.310 (1352793298)|STATEMENT_EXECUTE|[22]
- 13:16:06.310 (1352799838)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1352909886)|METHOD_EXIT|[22]|sdfs.FormulaShareTriggerHelper
- 13:16:06.310 (1358265667)|HEAP_ALLOCATE|[42]|Bytes:16
- 13:16:06.310 (1358829511)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1359282773)|HEAP_ALLOCATE|[77]|Bytes:12
- 13:16:06.310 (1359304083)|HEAP_ALLOCATE|[77]|Bytes:12
- 13:16:06.310 (1363433212)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1363499408)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1363613319)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1363705611)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1368839470)|SOQL_EXECUTE_BEGIN|[80]|Aggregations:0|SELECT Id, Access_Level__c, Object_Shared__r.QualifiedApiName, Object_Shared__r.MasterLabel, Shared_To__r.QualifiedApiName, Shared_To__r.MasterLabel, Share_With__c, Sharing_Reason__c, Active__c, Shared_To_Field_Type__c, Child_Object_with_Shared_To_Field__r.QualifiedApiName, Child_Object_with_Shared_To_Field__r.MasterLabel, Child_Object_Lookup_Field__r.QualifiedApiName, Child_Object_Shared_To_Field__r.QualifiedApiName, Child_Object_Shared_To_Field__r.MasterLabel, Child_Object_Shared_To_Field_Type__c, Contact_Access__c, Case_Access__c, Opportunity_Access__c, Shared_To__c, Child_Object_Shared_To_Field__c, MasterLabel, DeveloperName, Description__c FROM FormulaShare_Rule__mdt WHERE (Child_Object_with_Shared_To_Field__c = NULL AND Object_Shared__r.QualifiedApiName = :tmpVar1)
- 13:16:06.310 (1840711273)|SOQL_EXECUTE_END|[80]|Rows:1
- 13:16:06.310 (1841010124)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1841506546)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1841565765)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1842416270)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1844096728)|SOQL_EXECUTE_BEGIN|[103]|Aggregations:0|SELECT Id, Access_Level__c, Object_Shared__r.QualifiedApiName, Object_Shared__r.MasterLabel, Shared_To__r.QualifiedApiName, Shared_To__r.MasterLabel, Share_With__c, Sharing_Reason__c, Active__c, Shared_To_Field_Type__c, Child_Object_with_Shared_To_Field__r.QualifiedApiName, Child_Object_with_Shared_To_Field__r.MasterLabel, Child_Object_Lookup_Field__r.QualifiedApiName, Child_Object_Shared_To_Field__r.QualifiedApiName, Child_Object_Shared_To_Field__r.MasterLabel, Child_Object_Shared_To_Field_Type__c, Contact_Access__c, Case_Access__c, Opportunity_Access__c, Shared_To__c, Child_Object_Shared_To_Field__c, MasterLabel, DeveloperName, Description__c FROM FormulaShare_Rule__mdt WHERE (Child_Object_with_Shared_To_Field__c != NULL AND Child_Object_with_Shared_To_Field__r.QualifiedApiName = :tmpVar1)
- 13:16:06.310 (1851822721)|SOQL_EXECUTE_END|[103]|Rows:0
- 13:16:06.310 (1852008083)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1862714624)|CONSTRUCTOR_EXIT|[2]|01p4W00000Kg2Yi|<init>()|sdfs.FormulaShareHelper
- 13:16:06.310 (1862764949)|STATEMENT_EXECUTE|[3]
- 13:16:06.310 (1862822542)|METHOD_ENTRY|[3]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.getSharesToInsert()
- 13:16:06.310 (1862836572)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1862967662)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1864111801)|METHOD_EXIT|[3]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.getSharesToInsert()
- 13:16:06.310 (1864140292)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
- 13:16:06.310 (1864223493)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
- 13:16:06.310 (1864232942)|STATEMENT_EXECUTE|[4]
- 13:16:06.310 (1864267324)|METHOD_ENTRY|[4]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.getSharesToDelete()
- 13:16:06.310 (1864274918)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1864334359)|ENTERING_MANAGED_PKG|sdfs
- 13:16:06.310 (1864453875)|METHOD_EXIT|[4]|01p4W00000Kg2Yi|sdfs.FormulaShareHelper.getSharesToDelete()
- 13:16:06.310 (1864468469)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
- 13:16:06.310 (1864522324)|HEAP_ALLOCATE|[EXTERNAL]|Bytes:4
- 13:16:06.864 (1864535174)|CUMULATIVE_LIMIT_USAGE

The mystery is that both types of Volunteer Opportunities go through both of the scenarios listed above (quick exit vs. longer operation).

1. We're wondering if the trigger is getting thrown off because of something being Asynchronous.  
2. Or, maybe the share records are being created/deleted/created/deleted and then a row lock occurs which leaves the Share table in a deleted state?  
3. Or, maybe several DML operations are being done in a single transaction and something gets lost during the commit?  
4. Or, maybe the sobjects/sobjects/composite/sobjects order of API calls is resulting in an unexpected scenario?
5. Or, maybe another automation or workflow rule is throwing off the sequence?

The only thing that jumps out to me, when looking at the chronological sequence of all of the trigger executions from beginning to end in the debug logs, is I see an "on update" before an "on insert".

Peace,
Brian

**Comment by LawrenceLoz** [comment]
Hi @brian-summit 

Firstly apologies not to get back to you (much!) sooner, I must have missed the notification for this.

When you say multiple DML operations are occurring on the HOC__Volunteer_Opportunity__c object, do you mean within the same Salesforce transaction? This could be the case if your front end client is calling the composite API or possibly if there's some cascading DML.

Either way this could be causing false positives in the FormulaShare logic to reduce the risk of recursive updates. Right now FormulaShare will only process sharing assessment once per object per transaction - there's a static list of objects maintained in FormulaShareTriggerHelper which is checked before assessment is submitted, and an object will only be processed if its not been processed already in this transaction.

Are the full logs for a transaction consistent with this or is there something else which might be involved do you think?

Appreciate you might have sorted this out some way already, hopefully things are working well for you in any case!

All the best
Lawrence

**Comment by LawrenceLoz** [comment]
Hi @brian-summit 

Just to let you know I've changed the way recursion is handled so that this is assessed on a per-record basis, so provided your web service is creating or updating different records this should allow these to be processed even if this happens at different stages of the transaction.

I've also added a setting to disable the recursion protection completely (though from your description I'm hoping the per-record tweak resolves what you're seeing)

The changes are on this commit if you'd like to take a look: https://github.com/LawrenceLoz/FormulaShare-DX/commit/22744dd5a53fe0b469c33908d1f83f716502ebf6. I'll include this in the next production upgrade but let me know if you'd like to try this out in a pre-release version earlier than that.

Cheers
Lawrence

**Comment by LawrenceLoz** [comment]
Closing as this should be addressed now with improved recursion control

**Comment by brian-summit** [comment]
@LawrenceLoz -- We are currently using version 2.2 (Managed) and would like to upgrade.  Please let me know the upgrade procedure.

**Comment by LawrenceLoz** [comment]
Thanks @brian-summit, I've dropped you an email on this
