### ISSUE TITLE
Is anybody using this package?

### ISSUE THREAD

**Issue by deniskrizanovic** [LawrenceLoz/FormulaShare-DX#6]
It would be really good in the doco, if there was some insight into how many people are using this. A breakdown of how many rules are being executed would also be great.

It would help me make this decision about adopting this or not.

**Comment by LawrenceLoz** [comment]
Hey Denis thanks for the suggestion - I've added the current number of production subscribers to first paragraph the readme.

No data is collected from subscribers using FormulaShare so assessing metrics like number of rules per org isn't possible right now. I wouldn't rule it out but I'd be reluctant to put something like this in place - I think there's a confidence which comes from knowing the package is not communicating with systems outside of your org which is important for a tool of this kind.

If you're interested to understand typical scale, I can let you know that in the org I work with we have around 36 rules controlling sharing for 12 objects with numbers of records in the low millions for the larger objects.
