### ISSUE TITLE
Account sharing not possible

### ISSUE THREAD

**Issue by LawrenceLoz** [LawrenceLoz/FormulaShare-DX#7]
After setting up a rule with Account as the shared object, assessment of this rule will lead to an error and no sharing will be applied.

Capabilities are required to:
- Enable account sharing can be applied
- Allow related contact, opportunity and case sharing levels to be set on the rule, and these objects at the appropriate level
- Support management of updates to account sharing which already shares contacts, opportunities and cases at a different level to the rule being applied

**Comment by qswh** [comment]
@LawrenceLoz  hi, are you saying that account sharing doesn't work completely at the moment? Could you please advise when this feature will be enabled?

**Comment by LawrenceLoz** [comment]
Hi @qswh 

Actually the feature to address this issue was introduced in the latest version (v2.2, which has been the one on the AppExchange since 16 November)

I hadn't gotten around to updating the Github master until now, but this is now up to date too so I'll close the issue.

**Comment by LawrenceLoz** [comment]
Ability to share accounts and set related object access levels was introduced November 2020. Documentation here: https://cloudsundial.com/formulashare-account-sharing

**Comment by qswh** [comment]
Thanks a lot.
