### ISSUE TITLE
Allow sharing based on contents of objects related across schema

### ISSUE THREAD

**Issue by LawrenceLoz** [LawrenceLoz/FormulaShare-DX#8]
Support for two additional scenarios would be useful:

1. I want to share a record to users, roles or groups specified in records which are grandchildren, great-grandchildren etc of the record to be shared (sharing based on children is included in the Nov20 release)
2. I want to share a record to users, roles or groups specified in records which are children, grandchildren, great-grandchildren etc of the parent, grandparent, great-grandparent etc of the record to be shared

The diagrams below illustrate how relationships would need to be referenced for scenarios 1 and 2
![FormulaShare detail view wireframe - Export (1)](https://user-images.githubusercontent.com/32834730/96335693-4da66a00-1072-11eb-9427-dbf2756b49bf.png)
![FormulaShare detail view wireframe - Export](https://user-images.githubusercontent.com/32834730/96335631-fbfddf80-1071-11eb-898f-eab536563a67.png)

The examples above show 2 levels of parent and child relationships being used. Support for up to 5 levels of each would seem about right to keep this flexible without adding considerable complications to the implementation.

**Comment by acrosman** [comment]
This looks like a good feature. I would caution about the edge case for both scenarios where the admin wants to share SOME of the descendant and not others. Least being clear in docs about whether or not that's supported would be helpful.

**Comment by LawrenceLoz** [comment]
Thanks for the feedback @acrosman, this is really helpful.

Sharing conditionally for scenario 1 should be possible when the fields specifying the entities to get access (which would exist in the pink records) are formula fields. These could either populate or stay empty based on conditions using other fields on the record, or other related object fields accessible in formulas. If we're basing sharing on a field which isn't a formula field (a user lookup for example), then we could create a companion formula field which populates with that value only when other conditions are met as well.

This applies for some kinds of conditional use cases for scenario 2 as well. The exception would be if we wanted to use conditions based on values in the yellow or dark green object records. I guess a conditional filter when expressing the relationship would help here.

Once this is ready I'll make sure to document what is and isn't supported in terms of conditions and perhaps look to add relationship filter criteria as a second phase.

**Comment by LawrenceLoz** [comment]
This feature is now implemented as an extension in the FormulaShare app, which provides this capability through related object sharing
