### ISSUE TITLE
Deprecate sharing based on related objects

### ISSUE THREAD

**Issue by LawrenceLoz** [LawrenceLoz/FormulaShare-DX#84]
The capability to share records based on values of fields from other objects will be removed from the main branch of this repository by approximately early July 2022.

This change will mean the capability to select an object other than the object shared as the location of the field with the user, role or group to share to will be removed, and if the new version of the repo is deployed to an org which previously used an older version, any related object sharing rules won't work.

The ability to share based on a formula field which references information from a parent or ancestor object will remain as a way to reference values from these objects.

There are a few reasons for this change:

- Related object sharing is missing some key features in comparison to standard rules, particularly in terms of real time calculation. The lack of parity is the cause of some confusion and I regularly spend time looking into support requests related to this. Improving this area is something I'd really like to do, but it's a very complex thing to get implemented properly. To justify the effort to do this and continue to make other improvements I'd like to establish a more sustainable financial model around the managed package. FormulaShare will move to an open/closed model for the source code, with core FormulaShare capabilities remaining open source, but extensions which are offered on the AppExchange managed outside of the repo
- The current functionality involved in related object sharing is already by far the most complex area of the project and a significant amount of the codebase is dedicated to these features. With these extra components removed the footprint of the app will be reduced quite a bit, improving deployment time and apex test running times
- With fewer complex components, I hope the open source FormulaShare repo becomes more attractive to potential collaborators to continue extending the project

If you're currently using related object sharing in your rules, there will be some options around what to do next:

- Continue using the package version or version of the repository code you're currently on. Note that this version should be considered unsupported and no new features or fixes will be applied
- Fork the repository from any commit prior to the deprecation and continue development as a parallel project
- Consider upgrading to the Enterprise version of FormulaShare, which will be available on the AppExchange at the same time that the deprecation is implemented

If you'd like to understand more about any of these options or for any other questions feel free to comment below or raise a separate issue

**Comment by eyildirim81** [comment]
Hello LawrenceLoz
For my org use case, I would like to use FormulaShare app since I thought it would be a great solution for the access case.  I would like to share account records with the public groups but my group formula field is in the related object of Account. After I set up everything, I tested out the org but did not work. I made the account object private and did not give any access through the profile of the users. However, when I add the user to the sharing public group that user still cannot see the shared records.  I t would be really appreciated if you help me with the issue.
Thank you 
Elif

**Comment by LawrenceLoz** [comment]
Hi @eyildirim81 
Are you currently trying using the AppExchange app? We're in the process of finalising the new version referenced in this issue and will be changing the current listing over to this version in the next few days (the version currently on the AppExchange will be moving out of support). The new version has quite a lot of fundamental changes to the sharing engine so may solve your issue - the basic package will be free, though be aware this has some limitations around number of rules and number of records shared. If you'd interested to try a pre-release please email formulashare@cloudsundial.com and I can send you a pre-release version to try out
Best
Lawrence

**Comment by eyildirim81** [comment]
Hello LawrenceLoz,
Thank you for your quick response. Yes, I am using the AppExchange app. And yes I am interested to try the pre-release. I will send an email now.
Thank you again
