### ISSUE TITLE
Question: How to contribute to this project?

### ISSUE THREAD

**Issue by sfdcschwabe** [LawrenceLoz/FormulaShare-DX#9]
Hi Lawrence,

I really love the idea of this tool!
To be honest, I've less experience to contribute to a project in a repository. But I want to close this gap and like to ask if there is a way to learn to contribute to this project? Is there a small thing I can start to work on in this project to study the whole structure of this project?

A few things to myself:
I am a salesforce developer since more than five years and work on lwcs since publishing this new framework.

Best regards,
Christian

P.S.: Really love to hear back from you.

**Comment by LawrenceLoz** [comment]
Hi Christian,

Thanks for your question, it would be great to get your help to improve FormulaShare.

There are a few things which would be beneficial extensions to the project and would help to get to know how things work without needing an advanced understanding of every aspect. A few ideas:
 - Adding Jest tests for LWC components (currently there are none, so even one or two simple tests would be a big step forward)
 - Configuring a CI workflow to build to validate builds using Travis or similar
 - Creating an LWC component to show the current sharing and recent FormulaShare activity (from the log objects) for a given record

Of all of these I think the Jest tests could add the most value at this stage. If none of these appeal let me know as there could be other improvements we could look at together too.

Thanks for your interest and be great to collaborate!

Lawrence

@sfdcschwabe

**Comment by sfdcschwabe** [comment]
Hi Lawrence,

thanks for your response! I really like the idea to work on an open source project.

The easiest for me would be the third point ('Creating an LWC...'), but this is not about picking out the raisins, but about facing new challenges.
That's why I'm going to dedicate myself to the Jest-tests. For this I have only theoretical knowledge so far, but I want to try it. I think I have something to deal with that.

The next question concerns the further procedure:
-Should I create a new branch from 'master'?
-What should the branch be called best? JestTest?

Best regards,
Christian

**Comment by LawrenceLoz** [comment]
Thanks for getting back Christian, and all sounds great! I'm also new to Jest so we'll be learning together.

I suggest for now if you're happy to focus on tests for components involved in the main list view that would be ideal. The ones to look at would be:
formulaShareRulesPage
formulaShareRulesListView
formulaShareScheduleJobDescription
formulaShareNoRulesIllustration
formulaShareAbout

You can also probably understand these without having to know the detail of how the other components work.

I'm working on another branch at the moment to address issue 8 which includes changes to the rule detail page so it's probably best we wait until work has stabilised there before we look at this.

If you can create the branch from master that would be great. I'll create a new issue so we can use this reference in the branch name - if you could call the branch #010_Jest_Tests_List_Page or something that would work well I think.

Thanks and let me know if any questions or if you'd like to chat before you start (I'm actually relocating this week so time is difficult but I'll be more available from next week).

Looking forward to working together!

Best
Lawrence
